version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=temper_code_test
      - MYSQL_USER=temper_code_test
      - MYSQL_PASSWORD=good_luck
#    ports:
#      - "3306:3306"
    restart: always

  example-node:
    image: example-node
    build: images/example-node
    command: ["./example.js"]
    volumes:
      - ./data:/data

  example-python:
    image: example-python
    build: images/example-python
    command: ["./example.py"]
    volumes:
      - ./data:/data

  example-r:
    image: example-r
    build: images/example-r
    command: ["./example.R"]
    volumes:
      - ./data:/data
